# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	1791220331	access_token	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWMyODhlYjcxYTFhNGY5NGY4YThhYTkiLCJpYXQiOjE3OTExMzM5MzEsImV4cCI6MTc5MTIyMDMzMX0.5aGoflKGICOekg-wwq3pJmeMEtEoJXkPGGA9i_5-8cw
