# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	1791220275	access_token	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWMyODhiMzU0MTEyODI2ZDRiMjQ1ZDIiLCJpYXQiOjE3OTExMzM4NzUsImV4cCI6MTc5MTIyMDI3NX0.k6kD7oQ1hfMvbp-1iGTx7cGXZo6tSgae21l_FKq4oZA
