export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  sites: "/sites",
  widget: "/widget",
  crawlJobs: "/crawl-jobs",
  tenants: "/tenants",
  settings: "/settings",
  profile: "/profile",
  users: "/users",
  roles: "/roles",
  permissions: "/permissions",
} as const;
